/*
Navicat MySQL Data Transfer

Source Server         : localhost_3306
Source Server Version : 50505
Source Host           : localhost:3306
Source Database       : abada_db

Target Server Type    : MYSQL
Target Server Version : 50505
File Encoding         : 65001

Date: 2017-07-04 14:45:07
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `subjects`
-- ----------------------------
DROP TABLE IF EXISTS `subjects`;
CREATE TABLE `subjects` (
  `subject_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `subject_code` varchar(255) DEFAULT NULL,
  `subject_desc` varchar(255) DEFAULT NULL,
  `prereq` varchar(255) NOT NULL,
  `coreq` varchar(255) NOT NULL,
  `units` varchar(100) NOT NULL,
  `is_deleted` varchar(255) DEFAULT '0',
  `course_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`subject_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1225 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of subjects
-- ----------------------------
INSERT INTO `subjects` VALUES ('1', 'English A', 'Basic English Grammar', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('2', 'English 1', 'Communication Arts', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('3', 'CS 101', 'Computer Fundamentals', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('4', 'CS 102', 'Computer Programming 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('5', 'Mathematics 1', 'Basic Math', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('6', 'TypeWriting 1', 'Basic Typewriting', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('7', 'P.E 1', 'Physical Fitness', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('8', 'CMT/NSTP', 'National Service Training Program', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('9', 'English 2', 'Communication Arts 2', '2', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('10', 'CS 103', 'Computer Programming 2', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('11', 'CS 201', 'Data Structures and Algorithm', '3', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('12', 'Mathematics 2', 'College Algebra', '5', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('13', 'Natural Science 1', 'Biological Science', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('14', 'Social Arts 1', 'Personality Development and  Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('15', 'Human Relation', 'Human Relation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('16', 'P.E 2', 'Philipine Folk Dances', '7', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('18', 'CS206', 'Digital Design', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('19', 'CS 212', 'Database Management Systems', '11', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('20', 'CS 203', 'Programming Languages', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('21', 'English 3', 'World Literature', '9', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('22', 'Trigonometry', 'Trigonometry', '12', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('23', 'CS 202', 'Design & Analysis of Algorithm', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('24', 'CS 104', 'Discrete Structures', '12', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('25', 'Natural Science 2', 'Earth Science', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('26', 'Speech', 'Speech Improvement', '9', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('27', 'CS 205', 'Modelling and Simulation', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('28', 'P.E 3', 'Group Games/Driving', '16', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('29', 'Philippine Literature', 'Philippine Literature', '9', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('30', 'English 5a', 'Business Correspondence', '9', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('31', 'Statistics 1', 'Statistics and Probability', '12', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('32', 'Fundamentals of Problem Solving 1 & 2', 'Fundamentals of Problem Solving 1 & 2', '4', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('33', 'CS 204', 'Automata and Language Theory', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('34', 'CS 211', 'Object-Oriented Programming', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('35', 'P.E 4', 'Foreign Dances/Swimming', '16', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('36', 'Psychology 1', 'General Psychology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('37', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('38', 'Current Issues and Environmental Awareness', 'Current Issues and Environmental Awareness', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('39', 'CS 105', 'Computer Org. and Assembly Language', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('40', 'CS 214', 'Software Engineering', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('41', 'Sociology', 'General Sociology (with Family Planning)', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('42', 'Filipino 1', 'Gamiting Filipino/ Komposisyon at Pagbasa', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('43', 'CS 215', 'Artificial Intelligence', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('44', 'CS 104', 'Presentation Skills in Information Technology', '3', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('45', 'CS 207', 'Operating Systems', '4', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('46', 'Economics', 'Principles of Economics w/ Taxation and Agrarian Reform', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('47', 'CS 216', 'Parallel Computing', '24', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('48', 'CS 213', 'Web Programming', '20', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('49', 'Calculus', 'Calculus', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('50', 'Filipino 2', 'Kasanayan, Sining ng Pakikipagtalagtasan', '42', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('51', 'Rizal\'s Life', 'Rizal\'s Life, Works and Writings', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('52', 'OJT', 'Internship - Praticum', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('53', 'History 1', 'Phil. History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('54', 'CS 501', 'Thesis 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('55', 'CS 208', 'Network Principles and Programming', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('56', 'CS 106', 'Professional Ethics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('57', 'CS 303', 'Elective -Data Communications and Networking', '45', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('58', 'History 2', 'Phil. Gov\'t and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('59', 'CS 502', 'Thesis 2', '54', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('60', 'CS 304', 'Elective - Computational Method', '49', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('61', 'CS 402', 'Elective - Computer Graphics', '39', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('62', 'CS 403', 'Elective - Robot Modellling', '43', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('65', 'Filipino 1', 'Komunikasyon sa Akademikong Filipino', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('66', 'Math 1', 'Basic Math', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('67', 'Psychology 1', 'General Psychology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('68', 'Science 1', 'Biological Science', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('69', 'Education 1', 'Teaching as a Profession', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('70', 'P.E. 1', 'Physical Fitness', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('72', 'Filipino 2', 'Pagbasa at Pagsulat tungo sa Pananaliksik', '65', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('73', 'Science 2', 'Earth Science', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('74', 'Math 2', 'College Algebra', '66', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('75', 'Psychology 2', 'Child And Adolescent Development w/ Drug Education', '67', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('76', 'Filipino 4', 'Panimulang Lingwistika', '65', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('77', 'Development Reading', 'Development Reading', '64', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('78', 'P.E. 2', 'Philippine Folk Dances', '70', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('79', 'Literature 1', 'Philippine Literature', '71', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('80', 'Filipino 3', 'Masining na Pagpapahayag', '72', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('81', 'Education 2', 'Principle of Teaching 1 w/ field study', '69', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('82', 'Education 3', 'Educational Technology 1', '69', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('83', 'Development Reading 2', 'Development Reading 2', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('84', 'Filipino 5', 'Istruktura ng Wikang Filipino', '76', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('85', 'Filipino 6', 'Ang Kurikulom ng Filipino sa batayang antas ng Edukasyon', '76', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('86', 'P.E. 3', 'Group Games/Driving', '78', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('89', 'Literature 2', 'World Literature', '71', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('90', 'Filipino 7', 'Pagpapahalagang Pampanitikan', '76', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('91', 'Education 4', 'Principle of Teaching 2 w/ field study', '81', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('92', 'Education 5', 'Educational Technology 2', '82', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('93', 'Filipino 8', 'Pagtuturo ng at pagtataya sa Pakikinig at Pagsasalita', '84', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('94', 'Filipino 9', 'Pagtuturo ng at pagtataya sa Pagbasa at Pagsulat', '84', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('95', 'Education 6', 'Curriculum Development', '81', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('97', 'P.E. 4', 'Foreign Dances/Swimming', '78', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('101', 'Education 7', 'Facilitating Learning w/ field stud ', '91', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('102', 'Education 8', 'Assessment of Student Learning 1 w/ field study', '91', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('103', 'Computer 1', 'ICT 1', '96', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('104', 'Humanities', 'Music 1', '69', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('105', 'Filipino 10', 'Intro sa Pagsasalin', '90', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('106', 'Filipino 11', 'Intro sa Pananaliksik- Wika at Panitikan', '90', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('107', 'Filipino 12', 'Paghahanda at Evalwasyon ng Kagamitang Panturo', '93', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('108', 'Speech and Stage Arts', 'Speech and Stage Arts', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('110', 'Education 9', 'Measurement and Evaluation', '102', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('111', 'Education 10', 'Assessment of Student Learning 2 w/ field study', '102', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('112', 'Filipino 13', 'Intro sa Pamamahayag', '106', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('113', 'Education 11', 'Guidance and Counseling', '102', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('114', 'Filipino 14', 'Panunuring Pampanitikan', '106', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('115', 'Filipino 15', 'Sanaysay at Talumpati', '106', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('116', 'Filipino 16', 'Intro sa Pag-aaral ng Wika', '106', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('117', 'Computer 2', 'ICT 2', '103', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('118', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('119', 'Rizal\'s Life', 'Rizal\'s Life', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('120', 'History 1', 'Phil. History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('121', 'Social arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('122', 'Filipino 17', 'Maikling Kwento', '115', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('123', 'Filipino 18', 'Panulaang Filipino', '115', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('124', 'Professional Ethics', 'Professional Ethics', '113', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('125', 'Education 12', 'Practice Teaching', '113', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('126', 'Review 1', null, '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('127', 'Education 13', 'Social Dimension of Education w/ field study', '125', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('128', 'Filipino 20', 'Dula at Nobelang Filipino', '123', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('129', 'Filipino 21', 'Pagtuturo ng at Pagtataya sa Panitikan', '114', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('130', 'Filipino 22', 'Pampanitikan ng mga Umuunlad na  Bansa', '114', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('131', 'Special Topics', 'Special Topics', '125', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('132', 'History 2', 'Phil. Govt. and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('133', 'Review 2', null, '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('138', 'Psychology 1', 'General Psychology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('146', 'Psychology 2', 'Child And Adolescent Development w/ Drug Education', '138', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('147', 'Filipino 4', 'Panimulang Lingwistika', '136', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('148', 'Development Reading', 'Development Reading', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('150', 'Literature 1', 'Philippine Literature', '142', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('155', 'Filipino 5', 'Istruktura ng Wikang Filipino', '147', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('156', 'Filipino 6', 'Ang Kurikulom ng Filipino sa batayang antas ng Edukasyon', '147', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('159', 'Literature 2', 'World Literature', '142', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('160', 'Filipino 7', 'Pagpapahalagang Pampanitikan', '147', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('163', 'Filipino 8', 'Pagtuturo ng at pagtataya sa Pakikinig at Pagsasalita', '155', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('164', 'Filipino 9', 'Pagtuturo ng at pagtataya sa Pagbasa at Pagsulat', '155', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('172', 'Humanities', 'Music 1', '140', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('173', 'Filipino 10', 'Intro sa Pagsasalin', '160', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('174', 'Filipino 11', 'Intro sa Pananaliksik- Wika at Panitikan', '160', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('175', 'Filipino 12', 'Paghahanda at Evalwasyon ng Kagamitang Panturo', '163', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('176', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('179', 'Filipino 13', 'Intro sa Pamamahayag', '174', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('181', 'Filipino 14', 'Panunuring Pampanitikan', '174', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('182', 'Filipino 15', 'Sanaysay at Talumpati', '174', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('183', 'Filipino 16', 'Intro sa Pag-aaral ng Wika', '174', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('185', 'Rizal\'s Life', 'Rizal\'s Life', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('186', 'History 1', 'Phil. History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('187', 'Social arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('188', 'Filipino 17', 'Maikling Kwento', '182', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('189', 'Filipino 18', 'Panulaang Filipino', '182', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('190', 'Filipino 19', 'Pagbasa ng mga Obra Maestang Pilipino', '182', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('191', 'Professional Ethics', 'Professional Ethics', '180', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('193', 'Review 1', 'Review 1', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('195', 'Filipino 20', 'Dula at Nobelang Filipino', '189', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('196', 'Filipino 21', 'Pagtuturo ng at Pagtataya sa Panitikan', '181', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('197', 'Filipino 22', 'Pampanitikan ng mga Umuunlad na  Bansa', '181', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('198', 'Special Topics', 'Special Topics', '192', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('199', 'History 2', 'Phil. Govt. and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('200', 'Review 2', 'Review 2', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('201', 'Speech and Stage Arts', 'Speech and Stage Arts', '142', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('202', 'ENGL A', 'Basic English/ Grammar', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('203', 'FILI 1', 'Sining ng Pakikipagtalastasan', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('204', 'MATH 1', 'Business Math 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('205', 'PSHS', 'Principle of safety Hygiene & Sanitation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('206', 'TOUR 1', 'Principle of Tourism 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('207', 'SCIN 1', 'Environmental Science', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('208', 'LITE 1', 'Philippine Literature', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('210', 'ENGL 1', 'Communication Arts', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('211', 'FILI 2', 'Pagbasa/Pagsulat sa iba\'t ibang disiplina', '203', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('212', 'LOGI', 'Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('213', 'HARM 1', 'Culinary Arts and Sciences', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('214', 'TOUR 2', 'Principles of Tourism 2', '206', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('215', 'TYPE 1', 'Basic Typewriting', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('216', 'HUMA', 'Art Appreciation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('217', 'PE 2', 'Philippine & Foreign Dances', '141', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('218', 'ENGL 2', 'Communication Arts 2', '210', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('219', 'TOUR 3', 'Total Quality management', '214', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('220', 'HARM 2', 'Banquet, Function & Catering Services Procedures', '213', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('221', 'HARM 3', 'Food and Beverage Service procedures', '205', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('222', 'STAT 1', 'Business Statistics', '204', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('223', 'MGMT 1', 'Principles of Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('224', 'TOUR 4', 'Tourism planning and Development', '214', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('225', 'HBOR ', 'Human Behavior in organization', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('226', 'PE 3', 'Driving', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('227', 'COMP 1', 'Basic Computer Operations', '215', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('228', 'CUAN', 'Cultural Anthropology', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('229', 'TOUR 5', 'Entrepreneurship & Business Planning', '223', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('230', 'MKTG 1', 'Principle of Marketing', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('231', 'FNCE 1', 'Basic Finance', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('232', 'HARM 4', 'Housekeeping procedures', '205', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('233', 'BCOM', 'Busines Communication', '218', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('235', 'PE 4', 'Swimming', '217', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('236', 'PRAC 1', 'Practicum 1', '232', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('237', 'HARM 5', 'Front Office procedure', '227', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('238', 'PYSC 1', 'General Psychology', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('239', 'MISM', 'Management Information system', '227', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('240', 'ACCT 1', 'Basic Accounting', '204', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('241', 'HARM 6', 'Asian Cuisine 1 & 2 - Culinary', '221', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('242', 'HARM 7', 'Banquet and Catering Management', '220', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('243', 'SOC A', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('245', 'HIST 1', 'Phil. History, Government & Constitution', '232', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('246', 'HARM 8 ', 'Rooms Division Management & Control System', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('247', 'ECON 1', 'Basic Economics', '221', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('248', 'HARM 9', 'Food and Beverage Control system', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('249', 'HARM 10', 'Western Cuisine/International \nClassic Cuisine or Culinary', '241', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('250', 'HARM 11', 'Hospitality Orginizational Management', '223', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('251', 'SPCH', 'Speech Improvement', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('253', 'TOUR 6', 'Events Management ', '229', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('254', 'RIZAL', 'Life and Works of Rizal', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('255', 'PROF', 'Professional Ethics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('256', 'HARM 12', 'Hospitality Operation Management', '250', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('257', 'HARM 13', 'Convention Management', '250', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('258', 'PRAC 2', 'Hotel Practice/ Operation', '236', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('260', 'Math 1', 'Business Mathematics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('261', 'Finance 1', 'Basic Finance', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('262', 'Accounting 1', 'Fundamentals sof Accounting Part 1', '', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('264', 'Marketing 1', 'Principle of Marketing', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('268', 'Accounting 2', 'Fundamentals of Accounting Part II', '262', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('269', 'Management 1', 'Principle of Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('273', 'Economics', 'Principle of Economics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('274', 'FM 1', 'Financial Management 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('277', 'History 1', 'Philippine History Roots and Development', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('281', 'Taxation 1', 'Income Taxation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('282', 'FM 2', 'Financial Analysis & Reporting', '274', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('283', 'Public Finance', 'Public Finance', '261', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('288', 'Business Law 1', 'Obligation and Contract', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('289', 'FM 3', 'Banking & Financial Institution', '282', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('290', 'Entrepreneural Management', 'Entrepreneural Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('291', 'FM 4', 'Monetory Policy & Central Banking', '282', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('292', 'Taxation 2', 'Transfer and Business Taxation', '281', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('293', 'Math 4', 'Business Statistics', '280', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('295', 'Literature 1', 'World Literature', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('296', 'TQM', 'Total Quality Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('297', 'FM 5', 'Investment and Portfolio Management', '291', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('298', 'Cooperative Management', 'Cooperative Management', '291', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('300', 'Business Communication', 'Business Communication', '286', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('301', 'Sociology 1', 'General Sociology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('302', 'Psychology 1', 'General Psychology', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('304', 'Bus. Law 2', 'Partnership and Corporation Law', '288', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('306', 'Human Resource Management', 'Human Resource Management', '290', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('307', 'FM 6', 'Credit and Collection', '297', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('308', 'FS', 'Feasibility Study', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('309', 'Bus. Law 3', 'Negotiable Instrument Law', '304', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('310', 'Rizal\'s Life', 'Rizal\'s Life, Works and Writings', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('311', 'FM 7', 'Capital Markets', '296', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('312', 'Speech', 'Speech Improvement', '286', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('313', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('314', 'History 2', 'Phil. Gov\'t. and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('315', 'Social Arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('317', 'Social Responsibility & Good Governance', 'Social Responsibility & Good Governance', '311', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('318', 'Humanities', 'Art Appreciation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('319', 'Ethics', 'Professional Ethics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('320', 'FM 8', 'Strategic Financial Management', '311', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('321', 'FM 9', 'Treasury Management', '311', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('322', 'Current Issues and Environmental Awareness', 'Current Issues and Environmental Awareness', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('323', 'Practicum', 'Practicum', '', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('327', 'Computer 2', 'Fundamentals of Programming (with Pascal)', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('328', 'Mathematics 1', 'Basic Math', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('334', 'Computer 3', 'Quality Consssciousness Habits and Processes', '327', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('336', 'Computer 4', 'Data Structures', '327', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('337', 'Mathematics 2', 'College Algebra', '328', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('338', 'History 1', 'Phil. History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('339', 'Computer 5', 'Logic Design and Digital Computer Concepts', '327', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('340', 'P.E. 2', 'Foreign Dances', '331', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('342', 'Psychology 1', 'General Psychology with HIV/AIDS education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('343', 'Fundamentals of Prblem Solving 1 & 2', 'Fundamentals of Prblem Solving 1 & 2', '', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('345', 'Mathematics 3', 'Trigonometry/Analytic Geometry\r\n', '337', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('346', 'Computer 6', 'Design and Implementation of Programming Languages', '336', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('347', 'Computer 7', 'File Processing and Database System', '336', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('348', 'Computer 8', 'Design & Analysis of Algorithm', '336', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('349', 'P.E.3', 'Group Games and Rec. Activities', '340', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('350', 'Literature', 'Philippine Literature', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('351', 'Ethics', 'General and Professional Ethics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('352', 'Speech', 'Speech Improvement', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('353', 'Computer 9', 'Introduction to Computer Organization, Architectur and Machine Level Prog.', '339', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('354', 'Computer 10', 'Operating System', '346', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('355', 'Presentation Skills in Information Technology', 'Presentation Skills in Information Technology', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('356', 'Computer 13', 'Data Communications & Networking', '339', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('357', 'P.E. 4', 'Philippine Folk Dancing', '340', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('430', 'Psychology 1', 'General Psychology with HIV/AIDS education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('438', 'Psychology 2', 'Child and Adolescent Development w/ Drug Education', '430', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('439', 'English 3', 'Intro to Linguistics', '9', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('440', 'Developmental Reading', 'Developmental Reading', '427', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('442', 'Literature 1', 'Philippine Literature', '434', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('446', 'Development Reading 2\r\n', 'Development Reading 2\r\n', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('447', 'English 4', 'Structure of English', '434', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('448', 'English 5', 'Airo Asian Literature', '434', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('451', 'Literature 2', 'World Literature', '434', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('452', 'English 6', 'English and American Literature', '447', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('455', 'English 7', 'The Teaching of Speaking', '447', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('463', 'Humanities', 'Music 1', '432', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('464', 'English 9', 'Teaching, Listening and Reading', '455', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('465', 'English 10', 'Teaching of Literature', '494', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('466', 'English 11', 'Preparation & Evaluating of Instructional Materials', '454', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('467', 'Speech and Stage Arts', 'Speech and Stage Arts', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('471', 'English 12', 'Campus Journalism', '469', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('473', 'English 13', 'Mythology and Folklore', '447', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('474', 'English 14', 'Language Reasearch', '469', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('475', 'English 15', 'Language and Literature Assessment', '469', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('476', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('477', 'History 1', 'Phil History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('478', 'Rizal\'s Life', 'Rizal\'s Life', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('479', 'Social Arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('480', 'English 16', 'Remedial Instruction in English', '474', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('481', 'English 17', 'English skills and Proficiency', '474', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('483', 'Professional Ethics', null, '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('484', 'Educational 12', 'Practice Teaching', '472', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('485', 'Review 1', 'Review 1', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('486', 'History 2', 'Phil. Gov\'t. and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('488', 'English 18', 'Introduction to Stylistics', '481', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('490', 'English 19', 'translation and Editing of Text', '481', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('491', 'English 20', 'Creative Writing', '481', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('492', 'Special Topics', 'Special Topics', '484', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('493', 'Review 2', 'Review 2', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('494', 'English 8', 'Literary Criticism', '447', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('568', 'Psychology 1', 'General Psychology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('577', 'Psychology 2', 'Child and Adolescent Development w/ Drug Education', '568', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('578', 'Development Reading', 'Development Reading', '565', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('579', 'Biology 1', 'Organismic Biology', '569', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('581', 'Literature 1', 'Philippine Literature', '572', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('585', 'Chemistry 1', 'Inorganic Chemistry', '569', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('586', 'Zoology 1', 'Fundamentals Principles of Zoology', '', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('589', 'Literature 2', 'World Literature', '572', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('590', 'Chemistry 2', 'Organic Chemistry', '585', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('593', 'Biology 2', 'Plant and Animal Taxonomy', '579', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('600', 'History 1', 'Phil. History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('602', 'Humanities', 'Music 1', '570', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('603', 'Botany 1', 'General Botany', '579', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('605', 'Biology 3', 'Anatomy and Physiology', '593', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('610', 'Biology 4', 'Ecology', '593', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('612', 'Physics 1', 'Physics for Health Science', '574', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('613', 'Chemistry 3', 'Biochemistry', '590', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('614', 'Rizal\'s Life', 'Rizal\'s Life', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('615', 'History 2', 'Phil. Gov\'t and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('616', 'Social Arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('617', 'Teaching Strategies for Major field', 'Teaching Strategies for Major field', '607', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('618', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('619', 'Professional Ethics', 'Professional Ethics', '611', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('621', 'Review 1', 'Review 1', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('623', 'Chemistry 4', 'Analytical Chemistry', '613', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('624', 'Speech and Stage Arts', 'Speech and Stage Arts', '572', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('625', 'Physics 2', 'Physics for Health Science 2', '612', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('626', 'Special Topics', 'Special Topics', '620', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('627', 'Review 2', 'Review 2', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('628', null, 'Mathematics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('629', null, 'English', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('630', null, 'Science', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('631', null, 'Filipino', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('632', null, 'Civics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('633', null, 'Computer', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('634', null, 'Mother tongue', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('635', null, 'MAPEH(Music, Arts, PE, Health)', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('636', null, 'Christian living', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('637', null, 'Penmanship', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('638', null, 'Speech', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('639', null, 'Science lab/SRA', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('640', null, 'Phantom', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('641', null, 'Swimming', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('642', null, 'Dance enrichment', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('643', null, 'Sports enrichment (badminton, board games, footsal, kickball)', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('644', null, 'Speech enrichment', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('645', null, 'Art enrichment', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('646', null, 'Athletics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('647', null, 'Music enrichment', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('648', null, 'Oral Cummunication in Context', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('649', null, 'Komunikasyon at Pananaliksik sa Wika at Kulturang Pilipino', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('650', null, 'General Mathematics', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('651', null, 'Earth Science', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('652', null, 'Personal Development / Pansariling Kaunlaran', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('653', null, 'Understanding Culture, Society and Politics', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('654', null, 'Physical Education and Health', '', '', '2.22', '0', null);
INSERT INTO `subjects` VALUES ('655', null, 'Front Office Services NC II - Part 1', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('657', null, '21st Century Literature from the Philippines and the World', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('658', null, 'Introduction to the Philosophy of the Human Person / Pambungad sa Pilosopiya ng Tao', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('659', null, 'Disaster Readines and Risk Reduction', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('660', null, 'Reasearch in Daily Life 2', '666', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('661', null, 'Inquiries, Investigations and Immersion/Career Jumpstart Program', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('662', null, 'Front Office Services NC II - Part 3', '672', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('663', null, 'Event Management Services NC III - Part 2', '671', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('664', null, 'Reading and Writing Skills', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('665', null, 'Pagbasa at Pagsusuri ng ibat-ibang Teksto Tungo sa Pananaliksik\r\n', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('666', null, 'Statistics and Probability (Grade School)', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('667', null, 'Contemporary Philippine Arts from the Regions', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('668', null, 'English for Academic and Professional Purposes', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('669', null, 'Empowerment Technologies (E-Tech)', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('670', null, 'Research in Daily Life 1', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('671', '', 'Event Management Services NC III - Part 1', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('672', null, 'Front Office Services (NC II) - Part 2', '655', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('673', null, 'Media and Information Literacy', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('674', null, 'Entrepreneurship', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('675', null, 'Pagsulat sa Filipino sa Piling Larangan (Akademik)', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('676', null, 'Event Management Services NC III - Part 3', '663', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('677', null, 'Practicum and Assessment - Front Office', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('678', null, 'Practicum and Assessment - Event Management', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('679', null, 'Computer Programming (NC IV) - Part 2', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('680', null, 'Animation (NC II) - Part 1', '655', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('681', null, 'Computer Programming (NC IV) - part 3', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('682', null, 'Animation (NC II) - Part 2\r\n', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('683', null, 'Entrepreneurship(Grade School)', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('684', null, 'Pagsulat sa Filipino sa Piling Larangan (Akademik)', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('685', null, 'Animation (NC II) - Part 3', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('686', null, 'Practicum and Assessment - Computer Programming', '', '', '4.44	', '0', null);
INSERT INTO `subjects` VALUES ('687', null, 'Practicum and Assessment - Animation', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('688', null, 'Research Project', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('689', null, 'SRA English', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('690', null, 'SRA Math', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('691', null, 'Math Elective', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('692', null, 'Violin\r\n', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('693', null, 'History (Grade School)', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('694', null, 'Homeroom\r\n', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('695', null, 'Guidance Hour', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('696', null, 'Spanish', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('697', null, 'Speech (Grade School)', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('698', null, 'AP', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('699', null, 'EsP', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('700', null, 'Filipino (Grade school)', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('701', null, 'MAPEH', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('702', null, 'Foreign Language', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('703', null, 'Journalism(Grade School)', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('704', null, 'Pagbasa at Pagsusuri ng Iba\'t-ibang Teksto Tungo sa Pananaliksik', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('705', null, 'Contemporary Philippine Arts from the Regions', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('706', null, 'Organization and Management', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('707', null, 'Business Math (Grade School)', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('708', null, 'Fundamentals of Account, Business and Management 1', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('709', null, 'Fundamentals of Accounting, Business and Management 2', '708', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('710', null, 'Business Marketing', '709', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('711', null, 'Applied Economics', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('712', null, 'Business Finance', '708', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('713', null, 'Business Ethics and Social Responsibility', '708', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('714', null, 'Business Enterprise Simulation', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('715', null, 'Personal Development/Pansariling Kaunlaran', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('716', null, 'Disciplines and Ideas in Social Sciences', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('717', null, 'Philippine Politics and Governance', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('718', null, 'Physical Science', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('719', null, 'Creative Writing/Malikhaing Pagsulat', '657', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('720', null, 'Creative Nonfiction: The Literary Essay', '719', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('721', null, 'Trends, Networks and Critical Thinking in the 21st Centure Culture', '722', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('722', '', 'Introduction to the Philosophy of the Human Person/Pambungad sa Pilosopiya ng Tao', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('723', null, 'Disciplines and Ideas in the Social Sciences, Disciplines and Ideas in the Applied Social', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('724', null, 'Community Engagement, Solidarity and Citizenship', '723', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('725', null, 'Culminating Activity', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('726', null, 'Pre-Calculus', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('727', null, 'General Chemistry 1', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('728', null, '21st Centure Literature from the Philippines and the World', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('729', null, 'Disaster Readiness and Risk Reduction', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('730', null, 'General Physics 1', '726', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('731', null, 'General Biology 1', '', '', '4.44', '0', null);
INSERT INTO `subjects` VALUES ('734', 'IT 101', 'Computer Fundamentals', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('735', 'IT 102', 'Computer Programming 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('736', 'Mathematics 1', 'Basic Math', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('738', 'P. E. 1', 'Physical Fitness', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('742', 'IT 103', 'Computer Programmng 2', '735', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('743', 'History 1', 'Phil. History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('745', 'Mathematics 2', 'College Algebra', '736', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('746', 'Natural Science 1', 'Biological Science', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('747', 'P. E. 2', 'Philippine Folk Dances', '738', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('751', 'Social Arts 1', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('752', 'History 2', 'Phil. Gov\'t. and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('758', 'IT 105', 'Computer Organization & Assembly Language', '742', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('759', 'IT 104', 'Discrete Structures', '745', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('760', 'Natural Science 2', 'Earth Science', '746', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('761', 'IT 211', 'Object Oriented Programming', '742', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('762', 'P. E. 3', 'Group Games/Driving', '747', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('764', 'Economics', 'Principles of Economics w/ Taxation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('765', 'English 5a', 'Business Correspondence', '741', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('766', 'Statistics 1', 'Statistics Probability', '745', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('767', 'Sociology', 'General Sociology (with Family Planning)', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('768', 'IT 212', 'Database Management System', '758', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('769', 'IT 202', 'Operating System Application', '742', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('770', 'IT 203', 'Network Management', '758', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('771', 'P. E. 4', 'Foreign Dances/Swimming', '747', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('774', 'IT 303', 'Integrated Application Software/ Productivity Tools', '758', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('775', 'Psychology 1', 'General Psychology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('776', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('777', 'Rizal\'s Life', 'Rizal\'s Life, Works and Writings', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('778', 'IT 214', 'Web Development', '768', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('779', 'IT 204', 'System Analysis and Design', '758', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('780', 'IT 213', 'Database Management Systems 2', '768', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('781', 'IT 106', 'Professional Ethics', '742', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('783', 'IT 205', 'Software Engineering', '769', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('784', 'IT 215', 'Multimedia Systems', '769', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('785', 'IT 302', 'Management Information System', '770', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('788', 'IT 303', 'Advance Assembly Language Programming', '758', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('789', 'IT 304', 'Structure of Programming Languages', '761', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('791', 'Speech', 'Speech Improvement', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('792', 'IT 402', 'Computer Graphics', '778', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('793', 'IT 403', 'Data Communications & Networking', '770', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('794', 'IT 206', 'Capstone Project/Technoprenuership', '785', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('795', 'IT 401', 'Computational Method', '789', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('797', 'IT 500', 'Internship/OJT/Practicum', '', '', '9', '0', null);
INSERT INTO `subjects` VALUES ('801', 'Filipino 1', 'Sining ng Pakikipagtalastasan', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('802', 'Accounting 1', 'Fundamentals of Accounting Part 1', '', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('803', 'Mathematics 1', 'Business Mathematics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('804', 'Management 1', 'Management Principles & Practice', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('805', 'P. E. 1', 'Physical Fitness', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('809', 'Accounting 2', 'Fundamentals of Accounting Part 2', '802', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('810', 'Marketing 1', 'Principles of Marketing', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('812', 'Economics', 'Introduction to Economics with Land Reform and Taxation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('813', 'P. E. 2', 'Philippine Folk Dances', '805', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('816', 'Literature 1', 'Philippine Literature', '807', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('818', 'Psychology 1', 'General/Business Psychology', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('819', 'Finance 1', 'Basic Finance', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('820', 'Management 2', 'Human Behavior in Organization', '804', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('821', 'FAR 1', 'Financial Accounting and Reporting Part 1', '809', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('823', 'Economics 2', 'Microecnomic Theory & Practice', '812', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('824', 'P. E. 3', 'Group Games/Driving', '813', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('826', 'IT 1', 'Fundamentals of Computer Software and Applications', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('827', 'Accounting 3', 'Cost Accounting & Management', '821', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('828', 'Math 4', 'Business Statistics', '817', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('829', 'Business Law 1', 'Obligation and Contract', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('830', 'Taxation 1', 'Income Taxation', '809', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('831', 'FAR 2', 'Financial Accounting and Reporting Part 2', '821', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('832', 'FM 1', 'Financial Management 1', '819', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('833', 'P. E. 4', 'Foreign Dances/Swimming', '813', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('835', 'Sociology', 'Society and Culture with Family Planning & HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('836', 'Social Arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('837', 'Social Science 1', 'Phil. History with Politics and Governance', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('840', 'IT 2', 'Fundamentals of Programming and Database', '826', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('841', 'Bus. Law 2', 'Partnership and Corporation Law', '829', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('842', 'Taxation 2', 'Transfer & Business Taxation', '830', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('843', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('844', 'Natural Science 1', 'Biological Science', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('845', 'Economics 3', 'Macro-economics Theory and Practice', '823', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('846', 'Speech', 'Speech Improvement', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('847', 'Management Accounting', 'Management Accounting', '827', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('850', 'IT 3', 'Concept and Systems Analysis & Design', '840', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('851', 'Management 3', 'Production and Operations Management', '828', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('853', 'Natural Science 2', 'Earth Science', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('855', 'Bus. Law 3', 'Sales, Agency, Labor & Other Commercial Law', '841', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('856', 'Rizal', 'Rizal\'s Life', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('857', 'FAR 3', 'Financial Accounting & Reporting - Part 3', '831', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('861', 'IT 4', 'Accounting Information System', '850', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('862', 'Humanities', 'Art Appreciation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('863', 'Ethics', 'Professional Ethics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('864', 'Management 4', 'Good Governance and Social Responsibility', '851', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('865', 'ADFAR', 'Advance Financial Accounting & Reporting', '821', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('866', 'Quantitive Technique in Business', 'Quantitive Technique in Business', '828', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('867', 'IT 5', 'Advance Computer Applications for Accountants', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('869', 'Internal Auditing', 'Internal Auditing', '857', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('870', 'Accounting for Governmental, Not-for-Profit Entities and Specialized Industries', 'Accounting for Governmental, Not-for-Profit Entities and Specialized Industries', '865', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('871', 'Internship', 'Internship', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('873', 'Business Correspondence', 'Business Correspondence', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('874', 'Bus. Policy & Strategy', 'Bus. Policy & Strategy', '841', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('879', 'Psychology 1', 'General Psychology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('882', 'P. E. 1', 'Physical Fitness and Group Games', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('887', 'Psychology 2', 'Child and Adolescent Development w/ Drug Education', '879', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('888', 'Development Reading', 'Development Reading', '876', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('889', 'Botany 1', 'General Botany', '880', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('890', 'P. E. 2', 'Philippine & Foreign Dances', '882', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('891', 'Literature 1', 'Philippine Literature', '883', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('896', 'Biology 1', 'Organismic Biology', '882', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('897', 'P. E. 3', 'Driving', '890', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('900', 'Literature 2', 'World Literature', '883', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('904', 'Physics 1', 'Mechanics, Sound & Thermodynamics', '885', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('906', 'P. E. 4', 'Swimming', '890', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('912', 'Humanities', 'Music 1', '881', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('914', 'Zoology 1', 'Fundamental Principles of Zoology', '896', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('918', 'English 12', 'Campus Journalism', '900', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('920', 'Physics 2', 'Electricity, Magnetism & Optics', '904', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('921', 'Bio-Chemistry', 'Physico-chemical Phenomena in Living Matter', '901', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('923', 'Rizal\'s Life', 'Rizal\'s Life', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('924', 'History 1', 'Phil. History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('925', 'Social Arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('928', 'Teaching Strategies for Major Field', 'Teaching Strategies for Major Field', '916', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('929', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('930', 'Professional Ethcs', 'Professional Ethcs', '919', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('932', 'Review 1', 'Review 1', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('935', 'History 2', 'Phil. Gov\'t and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('936', 'Speech and Stage Arts', 'Speech and Stage Arts', '883', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('937', 'Basic Electronics', 'Basic Electronics', '920', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('938', 'Special Topics', 'Special Topics', '931', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('939', 'Review 2', 'Review 2', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('944', 'Psychology 1', 'General Psychology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('947', 'P. E. 1', 'Physical Fitness', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('952', 'Psychology 2', 'Child and Adolescent Development w/ Drug Education', '944', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('953', 'Social Studies 1', 'Geography 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('954', 'Development Reading', 'Development Reading', '941', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('955', 'P. E. 2', 'Philippine Folk Dance', '947', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('956', 'Literature 1', 'Philippine Literature', '948', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('960', 'Social Studies 2', 'World History and Civilization 1', '953', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('961', 'Social Studies 3', 'Geography 2', '953', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('962', 'P. E. 3', 'Group Games/Driving', '955', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('964', 'Literature 2', 'World Literature', '948', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('965', 'Social Studies 4', 'Comparative Government and Politics', '960', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('968', 'Social Studies 5', 'World History and Civilization 2', '960', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('969', 'Social Studies 6', 'Goegraphy 3', '961', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('970', 'P. E. 4', 'Foreign Dances/Swimming', '955', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('976', 'Humanities', 'Music 1', '946', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('977', 'Social Studies 8', 'Production of Social Studies Instructional Materials', '968', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('978', 'Speech and Stage Arts', 'Speech and Stage Arts', '948', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('982', 'Social Studies 9', 'Asian Studies', '977', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('984', 'Social Studies 10', 'Economic Planning and Strategy', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('985', 'Social Studies 11', 'Building Bridges Across the Social Science Discipline', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('986', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('987', 'History 1', 'Phil. History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('988', 'Rizal\'s Life', 'Rizal\'s Life', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('989', 'Social Arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('990', 'Social Studies 13', 'Law Related Studies', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('991', 'Social Studies 14', 'Research in Social Sciences', '983', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('992', 'Professional Ethics', 'Professional Ethics', '983', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('994', 'Review 1', 'Review 1', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('996', 'Social Studies 15', 'Socio-Cultural Antrhopology', '991', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('997', 'Social Studies 16', 'Assessment and Evaluation in Social Studies', '991', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('998', 'Social Studies 17', 'Trends and Issues in Social Studies', '991', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('999', 'Special Topics', 'Special Topics', '993', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1000', 'History 2', 'Phil. Gov\'t and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1001', 'Review 2', 'Review 2', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('1006', 'Psychology 1', 'General Psychology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1007', 'MAPE 1', 'Foundation of MAPE', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1012', 'MAPE 2', 'Philippine and Asian Music', '1007', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1013', 'MAPE 3', 'Anatomical, mechanical and Phsiological Bases of Movement', '1007', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1015', 'Educational Psychology', 'Child and Adolecvent Development with Drug Education', '1006', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1016', 'Typewritting 1', 'Basic Typewritting', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1017', 'PE2', 'Philippine Folk Dances', '1009', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('1018', 'DR1', 'Developmental Reading 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1019', 'Literature 1', 'Philippine Literature', '1011', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1022', 'MAPE 4', 'Gymnastics', '1012', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1023', 'MAPE5', 'Philippine fold dance and other dance forms', '1012', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1026', 'Literature 2', 'World Literature', '1010', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1029', 'MAPE 6', 'Solfeggio and Applied Piano', '1012', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1030', 'MAPE 7', 'Personal Community and Environmental Health', '1012', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1032', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1033', 'PE4', 'Foreign Dances/Swimming', '1012', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('1034', 'CMT/NSTP2', 'National Service Training Program', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1035', 'RIZAL', 'Rizals Life', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1037', 'Social Arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1040', 'Humanities', 'Music 1', '1008', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1041', 'MAPE 8', 'Team Sports(backetball, volleyball, soft ball)', '1030', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1042', 'MAPE 9', 'Aquatics(Swimming and other water activities)', '1030', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1043', 'MAPE 10', 'Integrated Music Theory', '1029', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1045', 'Speech and Stage Arts', 'Speech and Stage Arts', '1010', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1046', 'History 1', 'Philippine History Roots and Development', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1049', 'MAPE 11', 'Music Literature(Western Music)', '1040', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1050', 'MAPE 12', 'Safety Education and First Aid', '1030', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1051', 'MAPE 13', 'Methods and strategies in teaching MAPE', '1039', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1054', 'Education11', 'Guidance and Counsel', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1059', 'Psychology 1', 'General Phychology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1067', 'Psychology 2', 'Child and Adolescent Development w/ Drug Education', '1059', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1068', 'Developmental Reading 1', 'Developmental Reading 1', '1056', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1069', 'Biology 1 ', 'Organismic Biology', '1060', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('1071', 'Literature 1', 'Philipine Literature', '1063', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1076', 'Zoology 1', 'Fundamental Principles of Zoology', '', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('1079', 'Literature 2', 'World Literature', '1063', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1083', 'Biology 2', 'Plant and Animal Taxonomy', '1069', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('1089', 'Development reading 2', 'Development reading 2', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1091', 'Humanities', 'Music 1', '1061', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1092', 'Botany 1', 'General Botany ', '1069', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('1093', 'Biology 3', 'Anatomy and Physiology', '1063', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('1097', 'Biology 4 ', 'Ecology', '1063', '', '5', '0', null);
INSERT INTO `subjects` VALUES ('1099', 'Physics 1', 'Physics for Health Science', '1065', '', '4', '0', null);
INSERT INTO `subjects` VALUES ('1101', 'Rizal\'s Life ', 'Rizal\'s Life ', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1102', 'History 1', 'Phil. History Roots and Dev.', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1103', 'Social Arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1104', 'Teaching Strategies for major field', 'Teaching Strategies for major field', '1095', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1105', 'Logic', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1106', 'Professional Ethics', 'Professional Ethics', '1098', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1108', 'Review', 'Review', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('1110', 'Speech and Stage arts', 'Speech and Stage arts', '1063', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1111', 'History 2 ', 'Phil. Gov\'t and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1113', 'Special Topics', 'Special Topics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1114', 'Review 2', 'Review 2', '', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('1119', 'Finance 1', 'Basic Finance', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1120', 'Marketing', 'Business Mathematics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1125', 'Management 1', 'Principles of Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1127', 'Economic', ' Priniciples of Economics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1128', 'Marketing 2 ', 'Professinal Salesmanship', '1120', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1131', 'Literature 1', 'World Literature', '1123', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('1132', 'Accounting 1', 'Fundamentals Of Accoungting Part 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1133', 'Mat 3', 'Mathematics of Investment', '1126', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1134', 'Taxation 1', 'Income Taxation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1135', 'Marketing 3', 'Marketing Research', '1128', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1136', 'CB 1', 'Consumer Behavior', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1137', 'P.E. 3', 'Driving', '1129', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('1139', 'Accounting 2', 'Fundamentals of Accounting Part II', '1132', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1140', 'Business Law 1', 'Obligation and Contract', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1141', 'Marketing 4', 'Marketing Management', '1135', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1142', 'Entrpreneural Management', 'Entrpreneural Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1143', 'Marketing 5', 'Distributive Management', '1135', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1144', 'Math 4', 'Business Statistics', '1126', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1145', 'Taxation ', 'Transfer and Business Taxation', '1134', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1146', 'P.E. 4', 'Swimming ', '1129', '', '2', '0', null);
INSERT INTO `subjects` VALUES ('1147', 'TQM', 'Total Quality Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1148', 'Marcketing 6', 'Advertising', '1143', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1149', 'Sales Management', 'Sales Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1151', 'Business Communication', 'Business Communication', '1123', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1152', 'Sociology 1', 'General Sociology with HIV/AIDS Education', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1153', 'Psychology 1', 'General Phychology', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1154', 'History 1', 'Philippine History Roots and Development', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1155', 'Bus. Law 2', 'Partnership and Corporation Law', '1140', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1157', 'Human Resource Management', 'Human Resource Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1158', 'Marketing 7', 'Product Management', '1148', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1159', 'FS', 'Feasibility Study', '1148', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1160', 'Bus. Law 3', 'Negotiable Instrument Law', '1155', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1161', 'Rizal\'s Life', 'Rizal\'s Works and Writings', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1162', 'Marketing 8', 'Retail Management', '1148', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1163', 'Speech', 'Speech Improvement', '1123', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1164', 'Logic ', 'Introduction to Logic', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1165', 'History 2', 'Phil. Govt and Constitution', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1166', 'Social Arts', 'Personality Development and Human Relations', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1168', 'Social Responsibility & Good Governance', 'Social Responsibility & Good Governance', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1169', 'Humanities', 'Art Appreciation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1170', 'Ethics', 'Professional Ethics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1171', 'Marcketing 9', 'Strategic Marketing Management', '1162', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1172', 'marcketing 10', 'International Marketing', '1162', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1173', 'Current Issues and Environmental Awareness', 'Current Issues and Environmental Awareness', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1174', 'Business Practicum', 'Business Practicum', '', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('1190', 'History 1', 'Philippine History Roots and Development', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1194', 'Taxation 1', 'Income Taxation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1195', 'FM 2', 'Financial Analysis & Reporting', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1196', 'Public Finance', 'Public Finance', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1201', 'Finance 1', 'Basic Finance', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1202', 'Accounting 1', 'Fundamentals of Accounting Part 1', '', '', '6', '0', null);
INSERT INTO `subjects` VALUES ('1203', 'Marketing 1', 'Principles of Marketing', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1206', 'Accounting 2', 'Fundamentals of Accounting Part II', '1202', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1207', 'Management 1', 'Principles of Management', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1210', 'Economics', 'Principles of Economics', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1211', 'FM 1', 'Financial Management 1', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1214', 'History 1', 'Philippine History Roots and Development', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1218', 'Taxation 1', 'Income Taxation', '', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1219', 'FM 2', 'Financial Analysis & Reporting', '1211', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1220', 'Public Finance', 'Public Finance', '1201', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1223', 'Math 3', 'Mathematics of Investment', '74', '', '3', '0', null);
INSERT INTO `subjects` VALUES ('1224', 'Computer 1', 'Computer Fundamentals (w/ DOS)', '', '', '3', '0', null);
