<?php

	require_once("../support/config.php");
	if(!isLoggedIn()){
		toLogin();
		die();
	  }
	$errors="";
	$inputs=$_POST;
    $check=$con->myQuery("SELECT id,trade_comp,gas_name,bank_name,loan_bank_name,loan_ind_name,veh_brand,real_loc FROM interview_sheet WHERE loan_id=".$inputs['id'])->fetch(PDO::FETCH_ASSOC);
    $child=$con->myQuery("SELECT id FROM interview_child WHERE loan_id=".$inputs['id'])->fetch(PDO::FETCH_ASSOC);
    $sib=$con->myQuery("SELECT id FROM interview_sibling WHERE loan_id=".$inputs['id'])->fetch(PDO::FETCH_ASSOC);
    $char=$con->myQuery("SELECT id FROM interview_char WHERE loan_id=".$inputs['id'])->fetch(PDO::FETCH_ASSOC);
    // echo "<pre>";
    // var_dump($inputs['child_name']);die;
	// 	if($check['id']>='2'){
	// 		$status_id='1';
	// 	}else{
	// 		$status_id='0';
	// 	}
		if($errors!="")
		{
			Alert("You have the following errors: <br/>".$errors,"danger");
				if(empty($_POST['id'])){
				redirect("ci_checking_form.php");}
				else{
				redirect("ci_checking_form.php?id=".$_POST['id']."&tab=".$_POST['tab']);}
			die;
		}else{
            array_pop($inputs['child_name']);
            array_pop($inputs['child_age']);
            array_pop($inputs['child_stat']);
            array_pop($inputs['child_aff']);
            array_pop($inputs['sib_name']);
            array_pop($inputs['sib_con']);
            array_pop($inputs['sib_add']);
            array_pop($inputs['char_name']);
            array_pop($inputs['char_add']);
            array_pop($inputs['corpo_name']);
            array_pop($inputs['corpo_pos']);

            $trade_comp=count(explode(",",$check['trade_comp']));
            $trade_comp=$trade_comp-$inputs['del_trade'];
            unset($inputs['trade_comp'][$trade_comp]);
            unset($inputs['trade_tel'][$trade_comp]);
            unset($inputs['trade_con'][$trade_comp]);
            unset($inputs['trade_deal'][$trade_comp]);
            unset($inputs['trade_coll'][$trade_comp]);

            $trade_comp=count(explode(",",$check['gas_name']));
            $trade_comp=$trade_comp-$inputs['del_gas'];
            unset($inputs['gas_name'][$trade_comp]);
            unset($inputs['gas_tel'][$trade_comp]);
            unset($inputs['gas_con'][$trade_comp]);
            unset($inputs['gas_coll'][$trade_comp]);

            $trade_comp=count(explode(",",$check['bank_name']));
            $trade_comp=$trade_comp-$inputs['del_bank'];
            unset($inputs['bank_name'][$trade_comp]);
            unset($inputs['bank_branch'][$trade_comp]);
            unset($inputs['bank_acct'][$trade_comp]);
            unset($inputs['bank_date'][$trade_comp]);
            unset($inputs['bank_ave'][$trade_comp]);

            $trade_comp=count(explode(",",$check['loan_bank_name']));
            $trade_comp=$trade_comp-$inputs['del_loanbank'];
            unset($inputs['loan_bank_name'][$trade_comp]);
            unset($inputs['loan_bank_branch'][$trade_comp]);
            unset($inputs['loan_bank_fac'][$trade_comp]);
            unset($inputs['loan_bank_amt'][$trade_comp]);
            unset($inputs['loan_bank_term'][$trade_comp]);
            unset($inputs['loan_bank_date'][$trade_comp]);
            unset($inputs['loan_bank_bal'][$trade_comp]);

            $trade_comp=count(explode(",",$check['loan_ind_name']));
            $trade_comp=$trade_comp-$inputs['del_loanind'];
            unset($inputs['loan_ind_name'][$trade_comp]);
            unset($inputs['loan_ind_con'][$trade_comp]);
            unset($inputs['loan_ind_amt'][$trade_comp]);
            unset($inputs['loan_ind_term'][$trade_comp]);
            unset($inputs['loan_ind_date'][$trade_comp]);
            unset($inputs['loan_ind_bal'][$trade_comp]);

            $trade_comp=count(explode(",",$check['veh_brand']));
            $trade_comp=$trade_comp-$inputs['del_veh'];
            unset($inputs['veh_brand'][$trade_comp]);
            unset($inputs['veh_year'][$trade_comp]);
            unset($inputs['veh_bank'][$trade_comp]);
            unset($inputs['veh_amt'][$trade_comp]);
            unset($inputs['veh_term'][$trade_comp]);

            $trade_comp=count(explode(",",$check['real_loc']));
            $trade_comp=$trade_comp-$inputs['del_real'];
            unset($inputs['real_loc'][$trade_comp]);
            unset($inputs['real_sq'][$trade_comp]);
            unset($inputs['real_year'][$trade_comp]);
            unset($inputs['real_bank'][$trade_comp]);
            unset($inputs['real_amt'][$trade_comp]);
            unset($inputs['real_term'][$trade_comp]);

            $inputs['child_name']=implode(",",$inputs['child_name']);
            $inputs['child_age']=implode(",",$inputs['child_age']);
            $inputs['child_stat']=implode(",",$inputs['child_stat']);
            $inputs['child_aff']=implode(",",$inputs['child_aff']);
            $inputs['sib_name']=implode(",",$inputs['sib_name']);
            $inputs['sib_con']=implode(",",$inputs['sib_con']);
            $inputs['sib_add']=implode(",",$inputs['sib_add']);
            $inputs['char_name']=implode(",",$inputs['char_name']);
            $inputs['char_con']=implode(",",$inputs['char_con']);
            $inputs['char_add']=implode(",",$inputs['char_add']);
            $inputs['corpo_name']=implode(",",$inputs['corpo_name']);
            $inputs['corpo_pos']=implode(",",$inputs['corpo_pos']);
            $inputs['trade_comp']=implode(",",$inputs['trade_comp']);
            $inputs['trade_tel']=implode(",",$inputs['trade_tel']);
            $inputs['trade_con']=implode(",",$inputs['trade_con']);
            $inputs['trade_deal']=implode(",",$inputs['trade_deal']);
            $inputs['trade_coll']=implode(",",$inputs['trade_coll']);
            $inputs['gas_name']=implode(",",$inputs['gas_name']);
            $inputs['gas_tel']=implode(",",$inputs['gas_tel']);
            $inputs['gas_con']=implode(",",$inputs['gas_con']);
            $inputs['gas_coll']=implode(",",$inputs['gas_coll']);
            $inputs['bank_name']=implode(",",$inputs['bank_name']);
            $inputs['bank_branch']=implode(",",$inputs['bank_branch']);
            $inputs['bank_acct']=implode(",",$inputs['bank_acct']);
            $inputs['bank_date']=implode(",",$inputs['bank_date']);
            $inputs['bank_ave']=implode(",",$inputs['bank_ave']);
            $inputs['loan_bank_name']=implode(",",$inputs['loan_bank_name']);
            $inputs['loan_bank_branch']=implode(",",$inputs['loan_bank_branch']);
            $inputs['loan_bank_fac']=implode(",",$inputs['loan_bank_fac']);
            $inputs['loan_bank_amt']=implode(",",$inputs['loan_bank_amt']);
            $inputs['loan_bank_term']=implode(",",$inputs['loan_bank_term']);
            $inputs['loan_bank_date']=implode(",",$inputs['loan_bank_date']);
            $inputs['loan_bank_bal']=implode(",",$inputs['loan_bank_bal']);
            $inputs['loan_ind_name']=implode(",",$inputs['loan_ind_name']);
            $inputs['loan_ind_con']=implode(",",$inputs['loan_ind_con']);
            $inputs['loan_ind_amt']=implode(",",$inputs['loan_ind_amt']);
            $inputs['loan_ind_term']=implode(",",$inputs['loan_ind_term']);
            $inputs['loan_ind_date']=implode(",",$inputs['loan_ind_date']);
            $inputs['loan_ind_bal']=implode(",",$inputs['loan_ind_bal']);
            $inputs['veh_brand']=implode(",",$inputs['veh_brand']);
            $inputs['veh_year']=implode(",",$inputs['veh_year']);
            $inputs['veh_bank']=implode(",",$inputs['veh_bank']);
            $inputs['veh_amt']=implode(",",$inputs['veh_amt']);
            $inputs['veh_term']=implode(",",$inputs['veh_term']);
            $inputs['real_loc']=implode(",",$inputs['real_loc']);
            $inputs['real_sq']=implode(",",$inputs['real_sq']);
            $inputs['real_year']=implode(",",$inputs['real_year']);
            $inputs['real_bank']=implode(",",$inputs['real_bank']);
            $inputs['real_amt']=implode(",",$inputs['real_amt']);
            $inputs['real_term']=implode(",",$inputs['real_term']);
            // var_dump($inputs['gas_name']);die;
		$con->beginTransaction();
		try {
			if(empty($check)){
					$inputs['applied_by']=$_SESSION[WEBAPP]['user']['user_id'];
					$params1=array(
                    "loan_id"=>$inputs['id'],
					"applied_by"=>$inputs['applied_by'],
					"client_no"=>$inputs['client_no'],
					"nname"=>$inputs['nname'],
					"age"=>$inputs['age'],
					"civil_status"=>$inputs['civil_status'],
					"birthdate"=>$inputs['birthdate'],
					"birthplace"=>$inputs['birthplace'],
					"edu_att"=>$inputs['edu_att'],
					"school"=>$inputs['school'],
					"gsis_sss"=>$inputs['gsis_sss'],
					"dri_lic"=>$inputs['dri_lic'],
					"emp_name"=>$inputs['emp_name'],
                    "emp_leng"=>$inputs['emp_leng'],
                    "emp_add"=>$inputs['emp_add'],
                    "emp_con"=>$inputs['emp_con'],
					"emp_des"=>$inputs['emp_des'],
                    "emp_sal"=>$inputs['emp_sal'],
                    "emp_prev"=>$inputs['emp_prev'],
					"spouse_name"=>$inputs['spouse_name'],
					"spouse_nname"=>$inputs['spouse_nname'],
					"spouse_age"=>$inputs['spouse_age'],
					"spouse_civil_status"=>$inputs['spouse_civil_status'],
					"spouse_birthdate"=>$inputs['spouse_birthdate'],
					"spouse_birthplace"=>$inputs['spouse_birthplace'],
					"spouse_edu_att"=>$inputs['spouse_edu_att'],
					"spouse_school"=>$inputs['spouse_school'],
					"spouse_gsis_sss"=>$inputs['spouse_gsis_sss'],
					"spouse_dri_lic"=>$inputs['spouse_dri_lic'],
					"spouse_emp_name"=>$inputs['spouse_emp_name'],
                    "spouse_emp_leng"=>$inputs['spouse_emp_leng'],
                    "spouse_emp_add"=>$inputs['spouse_emp_add'],
                    "spouse_emp_con"=>$inputs['spouse_emp_con'],
					"spouse_emp_des"=>$inputs['spouse_emp_des'],
                    "spouse_emp_sal"=>$inputs['spouse_emp_sal'],
                    "spouse_emp_prev"=>$inputs['spouse_emp_prev'],
					"no_child"=>$inputs['no_child'],
					"fat_name"=>$inputs['fat_name'],
					"fat_age"=>$inputs['fat_age'],
					"fat_add"=>$inputs['fat_add'],
					"mom_name"=>$inputs['mom_name'],
					"mom_age"=>$inputs['mom_age'],
					"mom_add"=>$inputs['mom_add'],
					"no_sib"=>$inputs['no_sib'],
					"pres_add"=>$inputs['pres_add'],
                    "pres_tel_no"=>$inputs['pres_tel_no'],
                    "pres_cel_no"=>$inputs['pres_cel_no'],
					"pres_leng_stay"=>$inputs['pres_leng_stay'],
					"pres_acquire"=>$inputs['pres_acquire'],
					"pres_free_name"=>$inputs['pres_free_name'],
					"pres_free_rel"=>$inputs['pres_free_rel'],
					"pres_free_tel"=>$inputs['pres_free_tel'],
					"pres_rent_name"=>$inputs['pres_rent_name'],
					"pres_rent_pay"=>$inputs['pres_rent_pay'],
					"pres_rent_tel"=>$inputs['pres_rent_tel'],
					"pres_mort_name"=>$inputs['pres_mort_name'],
					"pres_mort_pay"=>$inputs['pres_mort_pay'],
					"pres_mort_tel"=>$inputs['pres_mort_tel'],
                    "prev_add"=>$inputs['prev_add'],
                    "other_add"=>$inputs['other_add'],
                    "other_tel_no"=>$inputs['other_tel_no'],
                    "other_cel_no"=>$inputs['other_cel_no'],
					"other_leng_stay"=>$inputs['other_leng_stay'],
                    "other_acquire"=>$inputs['other_acquire'],
					"other_free_name"=>$inputs['other_free_name'],
					"other_free_rel"=>$inputs['other_free_rel'],
					"other_free_tel"=>$inputs['other_free_tel'],
					"other_rent_name"=>$inputs['other_rent_name'],
					"other_rent_pay"=>$inputs['other_rent_pay'],
					"other_rent_tel"=>$inputs['other_rent_tel'],
					"other_mort_name"=>$inputs['other_mort_name'],
					"other_mort_pay"=>$inputs['other_mort_pay'],
					"other_mort_tel"=>$inputs['other_mort_tel'],
					"bus_name"=>$inputs['bus_name'],
					"org_type"=>$inputs['org_type'],
					"date_est"=>$inputs['date_est'],
					"bus_nat"=>$inputs['bus_nat'],
					"sing_name"=>$inputs['sing_name'],
					"part_name"=>$inputs['part_name'],
					"part_rel"=>$inputs['part_rel'],
					"corp_man_name"=>$inputs['corp_man_name'],
                    "corp_maj_name"=>$inputs['corp_maj_name'],
                    "off_add"=>$inputs['off_add'],
                    "off_tel_no"=>$inputs['off_tel_no'],
                    "off_cel_no"=>$inputs['off_cel_no'],
					"off_leng_stay"=>$inputs['off_leng_stay'],
					"off_acquire"=>$inputs['off_acquire'],
					"off_free_name"=>$inputs['off_free_name'],
					"off_free_rel"=>$inputs['off_free_rel'],
					"off_free_tel"=>$inputs['off_free_tel'],
					"off_rent_name"=>$inputs['off_rent_name'],
					"off_rent_pay"=>$inputs['off_rent_pay'],
					"off_rent_tel"=>$inputs['off_rent_tel'],
					"off_mort_name"=>$inputs['off_mort_name'],
					"off_mort_pay"=>$inputs['off_mort_pay'],
					"off_mort_tel"=>$inputs['off_mort_tel'],
                    "off_prev_add"=>$inputs['off_prev_add'],
                    "gar_add"=>$inputs['gar_add'],
                    "gar_tel_no"=>$inputs['gar_tel_no'],
                    "gar_cel_no"=>$inputs['gar_cel_no'],
					"gar_leng_stay"=>$inputs['gar_leng_stay'],
					"gar_acquire"=>$inputs['gar_acquire'],
					"gar_free_name"=>$inputs['gar_free_name'],
					"gar_free_rel"=>$inputs['gar_free_rel'],
					"gar_free_tel"=>$inputs['gar_free_tel'],
					"gar_rent_name"=>$inputs['gar_rent_name'],
					"gar_rent_pay"=>$inputs['gar_rent_pay'],
					"gar_rent_tel"=>$inputs['gar_rent_tel'],
					"gar_mort_name"=>$inputs['gar_mort_name'],
					"gar_mort_pay"=>$inputs['gar_mort_pay'],
					"gar_mort_tel"=>$inputs['gar_mort_tel'],
                    "gar_prev_add"=>$inputs['gar_prev_add'],
                    "sour_pay"=>$inputs['sour_pay'],
                    "loan_for"=>$inputs['loan_for'],
                    "court_case"=>$inputs['court_case'],
                    "int_type"=>$inputs['int_type'],
                    "informant"=>$inputs['informant'],
                    "bor_rel"=>$inputs['bor_rel'],
                    "int_date"=>$inputs['int_date'],
                    "corpo_name"=>$inputs['corpo_name'],
                    "corpo_pos"=>$inputs['corpo_pos'],
                    "trade_comp"=>$inputs['trade_comp'],
                    "trade_tel"=>$inputs['trade_tel'],
                    "trade_con"=>$inputs['trade_con'],
                    "trade_deal"=>$inputs['trade_deal'],
                    "trade_coll"=>$inputs['trade_coll'],
                    "gas_name"=>$inputs['gas_name'],
                    "gas_tel"=>$inputs['gas_tel'],
                    "gas_con"=>$inputs['gas_con'],
                    "gas_coll"=>$inputs['gas_coll'],
                    "bank_name"=>$inputs['bank_name'],
                    "bank_branch"=>$inputs['bank_branch'],
                    "bank_acct"=>$inputs['bank_acct'],
                    "bank_date"=>$inputs['bank_date'],
                    "bank_ave"=>$inputs['bank_ave'],
                    "loan_bank_name"=>$inputs['loan_bank_name'],
                    "loan_bank_branch"=>$inputs['loan_bank_branch'],
                    "loan_bank_fac"=>$inputs['loan_bank_fac'],
                    "loan_bank_amt"=>$inputs['loan_bank_amt'],
                    "loan_bank_term"=>$inputs['loan_bank_term'],
                    "loan_bank_date"=>$inputs['loan_bank_date'],
                    "loan_bank_bal"=>$inputs['loan_bank_bal'],
                    "loan_ind_name"=>$inputs['loan_ind_name'],
                    "loan_ind_con"=>$inputs['loan_ind_con'],
                    "loan_ind_amt"=>$inputs['loan_ind_amt'],
                    "loan_ind_term"=>$inputs['loan_ind_term'],
                    "loan_ind_date"=>$inputs['loan_ind_date'],
                    "loan_ind_bal"=>$inputs['loan_ind_bal'],
                    "veh_brand"=>$inputs['veh_brand'],
                    "veh_year"=>$inputs['veh_year'],
                    "veh_bank"=>$inputs['veh_bank'],
                    "veh_amt"=>$inputs['veh_amt'],
                    "veh_term"=>$inputs['veh_term'],
                    "real_loc"=>$inputs['real_loc'],
                    "real_sq"=>$inputs['real_sq'],
                    "real_year"=>$inputs['real_year'],
                    "real_bank"=>$inputs['real_bank'],
                    "real_amt"=>$inputs['real_amt'],
                    "real_term"=>$inputs['real_term'],
                    "proposal"=>$inputs['proposal'],
                    "term"=>$inputs['term'],
                    "purpose"=>$inputs['purpose'],
                    "dealer"=>$inputs['dealer'],
                    "salesman"=>$inputs['salesman']
					);
					$con->myQuery("INSERT INTO
								interview_sheet(
									loan_id,client_no,nname,age,civil_status,birthdate,birthplace,edu_att,school,gsis_sss,dri_lic,emp_name,emp_leng,emp_add,emp_con,emp_des,emp_sal,emp_prev,
                                    spouse_name,spouse_nname,spouse_age,spouse_civil_status,spouse_birthdate,spouse_birthplace,spouse_edu_att,spouse_school,spouse_gsis_sss,spouse_dri_lic,
                                    spouse_emp_name,spouse_emp_leng,spouse_emp_add,spouse_emp_con,spouse_emp_des,spouse_emp_sal,spouse_emp_prev,
                                    no_child,fat_name,fat_age,fat_add,mom_name,mom_age,mom_add,no_sib,
                                    pres_add,pres_tel_no,pres_cel_no,pres_leng_stay,pres_acquire,pres_free_name,pres_free_rel,pres_free_tel,pres_rent_name,pres_rent_pay,pres_rent_tel,
                                    pres_mort_name,pres_mort_pay,pres_mort_tel,prev_add,
                                    other_add,other_tel_no,other_cel_no,other_leng_stay,other_acquire,other_free_name,other_free_rel,other_free_tel,other_rent_name,other_rent_pay,other_rent_tel,
                                    other_mort_name,other_mort_pay,other_mort_tel,
                                    bus_name,org_type,date_est,bus_nat,sing_name,part_name,part_rel,corp_man_name,corp_maj_name,
                                    off_add,off_tel_no,off_cel_no,off_leng_stay,off_acquire,off_free_name,off_free_rel,off_free_tel,off_rent_name,off_rent_pay,off_rent_tel,
                                    off_mort_name,off_mort_pay,off_mort_tel,off_prev_add,
                                    gar_add,gar_tel_no,gar_cel_no,gar_leng_stay,gar_acquire,gar_free_name,gar_free_rel,gar_free_tel,gar_rent_name,gar_rent_pay,gar_rent_tel,
                                    gar_mort_name,gar_mort_pay,gar_mort_tel,gar_prev_add,
                                    sour_pay,loan_for,court_case,int_type,informant,bor_rel,int_date,corpo_name,corpo_pos,trade_comp,trade_tel,trade_con,trade_deal,trade_coll,
                                    gas_name,gas_tel,gas_con,gas_coll,bank_name,bank_branch,bank_acct,bank_date,bank_ave,loan_bank_name,loan_bank_branch,loan_bank_fac,
                                    loan_bank_amt,loan_bank_term,loan_bank_date,loan_bank_bal,loan_ind_name,loan_ind_con,loan_ind_amt,loan_ind_term,loan_ind_date,loan_ind_bal,
                                    veh_brand,veh_year,veh_bank,veh_amt,veh_term,real_loc,real_sq,real_year,real_bank,real_amt,real_term,
                                    proposal,term,purpose,dealer_id,salesman_id,
                                    date_applied,applied_by
								) VALUES(
                                    :loan_id,:client_no,:nname,:age,:civil_status,:birthdate,:birthplace,:edu_att,:school,:gsis_sss,:dri_lic,:emp_name,:emp_leng,:emp_add,:emp_con,:emp_des,:emp_sal,:emp_prev,
                                    :spouse_name,:spouse_nname,:spouse_age,:spouse_civil_status,:spouse_birthdate,:spouse_birthplace,:spouse_edu_att,:spouse_school,:spouse_gsis_sss,:spouse_dri_lic,
                                    :spouse_emp_name,:spouse_emp_leng,:spouse_emp_add,:spouse_emp_con,:spouse_emp_des,:spouse_emp_sal,:spouse_emp_prev,
                                    :no_child,:fat_name,:fat_age,:fat_add,:mom_name,:mom_age,:mom_add,:no_sib,
                                    :pres_add,:pres_tel_no,:pres_cel_no,:pres_leng_stay,:pres_acquire,:pres_free_name,:pres_free_rel,:pres_free_tel,:pres_rent_name,:pres_rent_pay,:pres_rent_tel,
                                    :pres_mort_name,:pres_mort_pay,:pres_mort_tel,:prev_add,
                                    :other_add,:other_tel_no,:other_cel_no,:other_leng_stay,:other_acquire,:other_free_name,:other_free_tel,:other_free_tel,:other_rent_name,:other_rent_pay,:other_rent_tel,
                                    :other_mort_name,:other_mort_pay,:other_mort_tel,
                                    :bus_name,:org_type,:date_est,:bus_nat,:sing_name,:part_name,:part_rel,:corp_man_name,:corp_maj_name,
                                    :off_add,:off_tel_no,:off_cel_no,:off_leng_stay,:off_acquire,:off_free_name,:off_free_rel,:off_free_tel,:off_rent_name,:off_rent_pay,:off_rent_tel,
                                    :off_mort_name,:off_mort_pay,:off_mort_tel,:off_prev_add,
                                    :gar_add,:gar_tel_no,:gar_cel_no,:gar_leng_stay,:gar_acquire,:gar_free_name,:gar_free_rel,:gar_free_tel,:gar_rent_name,:gar_rent_pay,:gar_rent_tel,
                                    :gar_mort_name,:gar_mort_pay,:gar_mort_tel,:gar_prev_add,
                                    :sour_pay,:loan_for,:court_case,:int_type,:informant,:bor_rel,:int_date,:corpo_name,:corpo_pos,:trade_comp,:trade_tel,:trade_con,:trade_deal,:trade_coll,
                                    :gas_name,:gas_tel,:gas_con,:gas_coll,:bank_name,:bank_branch,:bank_acct,:bank_date,:bank_ave,:loan_bank_name,:loan_bank_branch,:loan_bank_fac,
                                    :loan_bank_amt,:loan_bank_term,:loan_bank_date,:loan_bank_bal,:loan_ind_name,:loan_ind_con,:loan_ind_amt,:loan_ind_term,:loan_ind_date,:loan_ind_bal,
                                    :veh_brand,:veh_year,:veh_bank,:veh_amt,:veh_term,:real_loc,:real_sq,:real_year,:real_bank,:real_amt,:real_term,
                                    :proposal,:term,:purpose,:dealer,:salesman,
                                    CURDATE(),:applied_by
								)",$params1);
								// $con->myQuery("UPDATE client_list SET status_id=?
								// WHERE client_number=?",array($status_id,$inputs['client_no']));

			Alert("Successfully Added.","success");}
			else{
					$params1=array(
                        "loan_id"=>$inputs['id'],
                        "applied_by"=>$inputs['applied_by'],
                        "nname"=>$inputs['nname'],
                        "age"=>$inputs['age'],
                        "civil_status"=>$inputs['civil_status'],
                        "birthdate"=>$inputs['birthdate'],
                        "birthplace"=>$inputs['birthplace'],
                        "edu_att"=>$inputs['edu_att'],
                        "school"=>$inputs['school'],
                        "gsis_sss"=>$inputs['gsis_sss'],
                        "dri_lic"=>$inputs['dri_lic'],
                        "emp_name"=>$inputs['emp_name'],
                        "emp_leng"=>$inputs['emp_leng'],
                        "emp_add"=>$inputs['emp_add'],
                        "emp_con"=>$inputs['emp_con'],
                        "emp_des"=>$inputs['emp_des'],
                        "emp_sal"=>$inputs['emp_sal'],
                        "emp_prev"=>$inputs['emp_prev'],
                        "spouse_name"=>$inputs['spouse_name'],
                        "spouse_nname"=>$inputs['spouse_nname'],
                        "spouse_age"=>$inputs['spouse_age'],
                        "spouse_civil_status"=>$inputs['spouse_civil_status'],
                        "spouse_birthdate"=>$inputs['spouse_birthdate'],
                        "spouse_birthplace"=>$inputs['spouse_birthplace'],
                        "spouse_edu_att"=>$inputs['spouse_edu_att'],
                        "spouse_school"=>$inputs['spouse_school'],
                        "spouse_gsis_sss"=>$inputs['spouse_gsis_sss'],
                        "spouse_dri_lic"=>$inputs['spouse_dri_lic'],
                        "spouse_emp_name"=>$inputs['spouse_emp_name'],
                        "spouse_emp_leng"=>$inputs['spouse_emp_leng'],
                        "spouse_emp_add"=>$inputs['spouse_emp_add'],
                        "spouse_emp_con"=>$inputs['spouse_emp_con'],
                        "spouse_emp_des"=>$inputs['spouse_emp_des'],
                        "spouse_emp_sal"=>$inputs['spouse_emp_sal'],
                        "spouse_emp_prev"=>$inputs['spouse_emp_prev'],
                        "no_child"=>$inputs['no_child'],
                        "fat_name"=>$inputs['fat_name'],
                        "fat_age"=>$inputs['fat_age'],
                        "fat_add"=>$inputs['fat_add'],
                        "mom_name"=>$inputs['mom_name'],
                        "mom_age"=>$inputs['mom_age'],
                        "mom_add"=>$inputs['mom_add'],
                        "no_sib"=>$inputs['no_sib'],
                        "pres_add"=>$inputs['pres_add'],
                        "pres_tel_no"=>$inputs['pres_tel_no'],
                        "pres_cel_no"=>$inputs['pres_cel_no'],
                        "pres_leng_stay"=>$inputs['pres_leng_stay'],
                        "pres_acquire"=>$inputs['pres_acquire'],
                        "pres_free_name"=>$inputs['pres_free_name'],
                        "pres_free_rel"=>$inputs['pres_free_rel'],
                        "pres_free_tel"=>$inputs['pres_free_tel'],
                        "pres_rent_name"=>$inputs['pres_rent_name'],
                        "pres_rent_pay"=>$inputs['pres_rent_pay'],
                        "pres_rent_tel"=>$inputs['pres_rent_tel'],
                        "pres_mort_name"=>$inputs['pres_mort_name'],
                        "pres_mort_pay"=>$inputs['pres_mort_pay'],
                        "pres_mort_tel"=>$inputs['pres_mort_tel'],
                        "prev_add"=>$inputs['prev_add'],
                        "other_add"=>$inputs['other_add'],
                        "other_tel_no"=>$inputs['other_tel_no'],
                        "other_cel_no"=>$inputs['other_cel_no'],
                        "other_leng_stay"=>$inputs['other_leng_stay'],
                        "other_acquire"=>$inputs['other_acquire'],
                        "other_free_name"=>$inputs['other_free_name'],
                        "other_free_rel"=>$inputs['other_free_rel'],
                        "other_free_tel"=>$inputs['other_free_tel'],
                        "other_rent_name"=>$inputs['other_rent_name'],
                        "other_rent_pay"=>$inputs['other_rent_pay'],
                        "other_rent_tel"=>$inputs['other_rent_tel'],
                        "other_mort_name"=>$inputs['other_mort_name'],
                        "other_mort_pay"=>$inputs['other_mort_pay'],
                        "other_mort_tel"=>$inputs['other_mort_tel'],
                        "bus_name"=>$inputs['bus_name'],
                        "org_type"=>$inputs['org_type'],
                        "date_est"=>$inputs['date_est'],
                        "bus_nat"=>$inputs['bus_nat'],
                        "sing_name"=>$inputs['sing_name'],
                        "part_name"=>$inputs['part_name'],
                        "part_rel"=>$inputs['part_rel'],
                        "corp_man_name"=>$inputs['corp_man_name'],
                        "corp_maj_name"=>$inputs['corp_maj_name'],
                        "off_add"=>$inputs['off_add'],
                        "off_tel_no"=>$inputs['off_tel_no'],
                        "off_cel_no"=>$inputs['off_cel_no'],
                        "off_leng_stay"=>$inputs['off_leng_stay'],
                        "off_acquire"=>$inputs['off_acquire'],
                        "off_free_name"=>$inputs['off_free_name'],
                        "off_free_rel"=>$inputs['off_free_rel'],
                        "off_free_tel"=>$inputs['off_free_tel'],
                        "off_rent_name"=>$inputs['off_rent_name'],
                        "off_rent_pay"=>$inputs['off_rent_pay'],
                        "off_rent_tel"=>$inputs['off_rent_tel'],
                        "off_mort_name"=>$inputs['off_mort_name'],
                        "off_mort_pay"=>$inputs['off_mort_pay'],
                        "off_mort_tel"=>$inputs['off_mort_tel'],
                        "off_prev_add"=>$inputs['off_prev_add'],
                        "gar_add"=>$inputs['gar_add'],
                        "gar_tel_no"=>$inputs['gar_tel_no'],
                        "gar_cel_no"=>$inputs['gar_cel_no'],
                        "gar_leng_stay"=>$inputs['gar_leng_stay'],
                        "gar_acquire"=>$inputs['gar_acquire'],
                        "gar_free_name"=>$inputs['gar_free_name'],
                        "gar_free_rel"=>$inputs['gar_free_rel'],
                        "gar_free_tel"=>$inputs['gar_free_tel'],
                        "gar_rent_name"=>$inputs['gar_rent_name'],
                        "gar_rent_pay"=>$inputs['gar_rent_pay'],
                        "gar_rent_tel"=>$inputs['gar_rent_tel'],
                        "gar_mort_name"=>$inputs['gar_mort_name'],
                        "gar_mort_pay"=>$inputs['gar_mort_pay'],
                        "gar_mort_tel"=>$inputs['gar_mort_tel'],
                        "gar_prev_add"=>$inputs['gar_prev_add'],
                        "sour_pay"=>$inputs['sour_pay'],
                        "loan_for"=>$inputs['loan_for'],
                        "court_case"=>$inputs['court_case'],
                        "int_type"=>$inputs['int_type'],
                        "informant"=>$inputs['informant'],
                        "bor_rel"=>$inputs['bor_rel'],
                        "int_date"=>$inputs['int_date'],
                        "corpo_name"=>$inputs['corpo_name'],
                        "corpo_pos"=>$inputs['corpo_pos'],
                        "trade_comp"=>$inputs['trade_comp'],
                        "trade_tel"=>$inputs['trade_tel'],
                        "trade_con"=>$inputs['trade_con'],
                        "trade_deal"=>$inputs['trade_deal'],
                        "trade_coll"=>$inputs['trade_coll'],
                        "gas_name"=>$inputs['gas_name'],
                        "gas_tel"=>$inputs['gas_tel'],
                        "gas_con"=>$inputs['gas_con'],
                        "gas_coll"=>$inputs['gas_coll'],
                        "bank_name"=>$inputs['bank_name'],
                        "bank_branch"=>$inputs['bank_branch'],
                        "bank_acct"=>$inputs['bank_acct'],
                        "bank_date"=>$inputs['bank_date'],
                        "bank_ave"=>$inputs['bank_ave'],
                        "loan_bank_name"=>$inputs['loan_bank_name'],
                        "loan_bank_branch"=>$inputs['loan_bank_branch'],
                        "loan_bank_fac"=>$inputs['loan_bank_fac'],
                        "loan_bank_amt"=>$inputs['loan_bank_amt'],
                        "loan_bank_term"=>$inputs['loan_bank_term'],
                        "loan_bank_date"=>$inputs['loan_bank_date'],
                        "loan_bank_bal"=>$inputs['loan_bank_bal'],
                        "loan_ind_name"=>$inputs['loan_ind_name'],
                        "loan_ind_con"=>$inputs['loan_ind_con'],
                        "loan_ind_amt"=>$inputs['loan_ind_amt'],
                        "loan_ind_term"=>$inputs['loan_ind_term'],
                        "loan_ind_date"=>$inputs['loan_ind_date'],
                        "loan_ind_bal"=>$inputs['loan_ind_bal'],
                        "veh_brand"=>$inputs['veh_brand'],
                        "veh_year"=>$inputs['veh_year'],
                        "veh_bank"=>$inputs['veh_bank'],
                        "veh_amt"=>$inputs['veh_amt'],
                        "veh_term"=>$inputs['veh_term'],
                        "real_loc"=>$inputs['real_loc'],
                        "real_sq"=>$inputs['real_sq'],
                        "real_year"=>$inputs['real_year'],
                        "real_bank"=>$inputs['real_bank'],
                        "real_amt"=>$inputs['real_amt'],
                        "real_term"=>$inputs['real_term'],
                        "proposal"=>$inputs['proposal'],
                        "term"=>$inputs['term'],
                        "purpose"=>$inputs['purpose'],
                        "dealer"=>$inputs['dealer'],
                        "salesman"=>$inputs['salesman']
					);
					$con->myQuery("UPDATE
								interview_sheet SET
                                loan_id=:loan_id,nname=:nname,age=:age,civil_status=:civil_status,birthdate=:birthdate,birthplace=:birthplace,edu_att=:edu_att,
                                school=:school,gsis_sss=:gsis_sss,dri_lic=:dri_lic,emp_name=:emp_name,emp_leng=:emp_leng,emp_add=:emp_add,emp_con=:emp_con,emp_des=:emp_des,emp_sal=:emp_sal,emp_prev=:emp_prev,
                                spouse_name=:spouse_name,spouse_nname=:spouse_nname,spouse_age=:spouse_age,spouse_civil_status=:spouse_civil_status,spouse_birthdate=:spouse_birthdate,spouse_birthplace=:spouse_birthplace,
                                spouse_edu_att=:spouse_edu_att,spouse_school=:spouse_school,spouse_gsis_sss=:spouse_gsis_sss,spouse_dri_lic=:spouse_dri_lic,
                                spouse_emp_name=:spouse_emp_name,spouse_emp_leng=:spouse_emp_leng,spouse_emp_add=:spouse_emp_add,spouse_emp_con=:spouse_emp_con,spouse_emp_des=:spouse_emp_des,
                                spouse_emp_sal=:spouse_emp_sal,spouse_emp_prev=:spouse_emp_prev,no_child=:no_child,fat_name=:fat_name,fat_age=:fat_age,fat_add=:fat_add,mom_name=:mom_name,mom_age=:mom_age,mom_add=:mom_add,no_sib=:no_sib,
                                pres_add=:pres_add,pres_tel_no=:pres_tel_no,pres_cel_no=:pres_cel_no,pres_leng_stay=:pres_leng_stay,pres_acquire=:pres_acquire,pres_free_name=:pres_free_name,
                                pres_free_rel=:pres_free_rel,pres_free_tel=:pres_free_tel,pres_rent_name=:pres_rent_name,pres_rent_pay=:pres_rent_pay,pres_rent_tel=:pres_rent_tel,
                                pres_mort_name=:pres_mort_name,pres_mort_pay=:pres_mort_pay,pres_mort_tel=:pres_mort_tel,prev_add=:prev_add,
                                other_add=:other_add,other_tel_no=:other_tel_no,other_cel_no=:other_cel_no,other_leng_stay=:other_leng_stay,other_acquire=:other_acquire,other_free_name=:other_free_name,
                                other_free_rel=:other_free_rel,other_free_tel=:other_free_tel,other_rent_name=:other_rent_name,other_rent_pay=:other_rent_pay,other_rent_tel=:other_rent_tel,
                                other_mort_name=:other_mort_name,other_mort_pay=:other_mort_pay,other_mort_tel=:other_mort_tel,
                                bus_name=:bus_name,org_type=:org_type,date_est=:date_est,bus_nat=:bus_nat,sing_name=:sing_name,part_name=:part_name,part_rel=:part_rel,corp_man_name=:corp_man_name,corp_maj_name=:corp_maj_name,
                                off_add=:off_add,off_tel_no=:off_tel_no,off_cel_no=:off_cel_no,off_leng_stay=:off_leng_stay,off_acquire=:off_acquire,off_free_name=:off_free_name,off_free_rel=:off_free_rel,off_free_tel=:off_free_tel,
                                off_rent_name=:off_rent_name,off_rent_pay=:off_rent_pay,off_rent_tel=:off_rent_tel,off_mort_name=:off_mort_name,off_mort_pay=:off_mort_pay,off_mort_tel=:off_mort_tel,off_prev_add=:off_prev_add,
                                gar_add=:gar_add,gar_tel_no=:gar_tel_no,gar_cel_no=:gar_cel_no,gar_leng_stay=:gar_leng_stay,gar_acquire=:gar_acquire,gar_free_name=:gar_free_name,gar_free_rel=:gar_free_rel,gar_free_tel=:gar_free_tel,
                                gar_rent_name=:gar_rent_name,gar_rent_pay=:gar_rent_pay,gar_rent_tel=:gar_rent_tel,gar_mort_name=:gar_mort_name,gar_mort_pay=:gar_mort_pay,gar_mort_tel=:gar_mort_tel,gar_prev_add=:gar_prev_add,
                                sour_pay=:sour_pay,loan_for=:loan_for,court_case=:court_case,int_type=:int_type,informant=:informant,bor_rel=:bor_rel,int_date=:int_date,corpo_name=:corpo_name,corpo_pos=:corpo_pos,
                                trade_comp=:trade_comp,trade_tel=:trade_tel,trade_con=:trade_con,trade_deal=:trade_deal,trade_coll=:trade_coll,
                                gas_name=:gas_name,gas_tel=:gas_tel,gas_con=:gas_con,gas_coll=:gas_coll,bank_name=:bank_name,bank_branch=:bank_branch,bank_acct=:bank_acct,bank_date=:bank_date,bank_ave=:bank_ave,
                                loan_bank_name=:loan_bank_name,loan_bank_branch=:loan_bank_branch,loan_bank_fac=:loan_bank_fac,loan_bank_amt=:loan_bank_amt,loan_bank_term=:loan_bank_term,loan_bank_date=:loan_bank_date,loan_bank_bal=:loan_bank_bal,
                                loan_ind_name=:loan_ind_name,loan_ind_con=:loan_ind_con,loan_ind_amt=:loan_ind_amt,loan_ind_term=:loan_ind_term,loan_ind_date=:loan_ind_date,loan_ind_bal=:loan_ind_bal,
                                veh_brand=:veh_brand,veh_year=:veh_year,veh_bank=:veh_bank,veh_amt=:veh_amt,veh_term=:veh_term,
                                real_loc=:real_loc,real_sq=:real_sq,real_year=:real_year,real_bank=:real_bank,real_amt=:real_amt,real_term=:real_term,
                                proposal=:proposal,term=:term,purpose=:purpose,dealer_id=:dealer,salesman_id=:salesman,
                                date_applied=CURDATE(),applied_by=:applied_by
								WHERE loan_id=:loan_id
                                ",$params1);
                                //CHILDREN//
            if(empty($child)){
                $params1=array(
                    "loan_id"=>$inputs['id'],
                    "name"=>$inputs['child_name'],
                    "age"=>$inputs['child_age'],
                    "stat"=>$inputs['child_stat'],
                    "aff"=>$inputs['child_aff']
                );
                $con->myQuery("INSERT INTO
                interview_child(
                    loan_id,name,age,status,affiliation
                ) VALUES(
                    :loan_id,:name,:age,:stat,:aff
                )",$params1);
            }else{
                $params1=array(
                    "loan_id"=>$inputs['id'],
                    "name"=>$inputs['child_name'],
                    "age"=>$inputs['child_age'],
                    "stat"=>$inputs['child_stat'],
                    "aff"=>$inputs['child_aff']
                );
                $con->myQuery("UPDATE
                interview_child SET
                name=:name,age=:age,status=:stat,affiliation=:aff
                WHERE loan_id=:loan_id
                ",$params1);
            }
            if(empty($sib)){
                $params1=array(
                    "loan_id"=>$inputs['id'],
                    "name"=>$inputs['sib_name'],
                    "con"=>$inputs['sib_con'],
                    "add"=>$inputs['sib_add']
                );
                $con->myQuery("INSERT INTO
                interview_sibling(
                    loan_id,name,contact,address
                ) VALUES(
                    :loan_id,:name,:con,:add
                )",$params1);
            }else{
                $params1=array(
                    "loan_id"=>$inputs['id'],
                    "name"=>$inputs['sib_name'],
                    "con"=>$inputs['sib_con'],
                    "add"=>$inputs['sib_add']
                );
                $con->myQuery("UPDATE
                interview_sibling SET
                name=:name,contact=:con,address=:add
                WHERE loan_id=:loan_id
                ",$params1);
            }
            if(empty($char)){
                $params1=array(
                    "loan_id"=>$inputs['id'],
                    "name"=>$inputs['char_name'],
                    "con"=>$inputs['char_con'],
                    "add"=>$inputs['char_add']
                );
                $con->myQuery("INSERT INTO
                interview_char(
                    loan_id,name,contact,address
                ) VALUES(
                    :loan_id,:name,:con,:add
                )",$params1);
            }else{
                $params1=array(
                    "loan_id"=>$inputs['id'],
                    "name"=>$inputs['char_name'],
                    "con"=>$inputs['char_con'],
                    "add"=>$inputs['char_add']
                );
                $con->myQuery("UPDATE
                interview_char SET
                name=:name,contact=:con,address=:add
                WHERE loan_id=:loan_id
                ",$params1);
            }
            Alert("Successfully Updated.","success");}
			$con->commit();
			redirect("ci_checking_form.php?id=".$inputs['id']."&tab=".$inputs['tab']);
			die;
		} catch (Exception $e) {
			$db->rollBack();
			Alert('Please try again.',"danger");
            redirect("ci_checking_form.php?id=".$inputs['id']."&tab=".$inputs['tab']);
			die;
		}
	}
?>

